### ISSUE TITLE
2 million users

### ISSUE THREAD

**Issue by harry-wood** [osm-cwg/posts#1]
We'll hit 2 million users some time in the next week perhaps!? http://osmstats.neis-one.org 
(although the sysadmins may do a spam user account cull beforehand)

So we need a blog post about hitting 2 million users

**Comment by hbogner** [comment]
Just an update: Number of registered OSM members: 1960788

**Comment by hbogner** [comment]
2000199

**Comment by hbogner** [comment]
Reminder, we passed 2 million on March 8th. Anyone want to write this? I can't do it this week, only in a week or so.

**Comment by harry-wood** [comment]
Crap. Missed this completely. We should've tweeted the news on the day. Anyway for the blog post Richard Weait has emailed us with a draft.
https://hackpad.com/Two-million-OpenStreetMap-contributors-rlKn47vOxSB

I will post this in the next few hours unless there's objections/changes to be discussion

**Comment by harry-wood** [comment]
posted yesterday https://blog.openstreetmap.org/2015/03/12/two-million-contributors/
