### ISSUE TITLE
MapMyDay

### ISSUE THREAD

**Issue by harry-wood** [osm-cwg/posts#11]
blog post about mapMyDay.  It's on December 3rd (blog post should be ready to post that morning)

 https://hackpad.com/MapMyDay-CHsQFH67W6h (currently empty)

**Comment by chrisfleming** [comment]
I've put something up onto the Hackpad, I'll have another pass over it in the morning, but it could do with another set of eyes.

**Comment by chrisfleming** [comment]
Posted, hope it's okay,

**Comment by harry-wood** [comment]
Nice one @chrisfleming   Thanks for doing that!
