### ISSUE TITLE
The Iceland Local Chapter

### ISSUE THREAD

**Issue by hbogner** [osm-cwg/posts#3]
Here is a mail from Paul Norman:

Hello CWG,
The Iceland Local Chapter application is nearly finished. Although I can announce it myself, I'm thinking this is a chance for some chances for news about the foundation and what it's doing, and get more groups to apply (http://wiki.osmfoundation.org/wiki/Local_Chapters/FAQ#Applying_to_become_a_local_chapter).

I've cc'ed Jóhannes of Hliðskjálf for coordination.

**Comment by harry-wood** [comment]
A low key announcement was posted to the mailing list https://lists.openstreetmap.org/pipermail/osmf-talk/2015-February/003241.html

Does anyone have a starting point on writing a blog post about this? If not we could take that mailing list post as a starting point. Maybe just lift a little more detail off the linked web page. Someone want to do that in a hackpad?

**Comment by hbogner** [comment]
Sorry, won't be able to help in next few weeks.

**Comment by harry-wood** [comment]
OK so this is the hackpad for this blog post:

https://hackpad.com/OpenStreetMap-Local-Chapters-Welcome-Iceland-EcANAnsAtVT

**Comment by harry-wood** [comment]
DONE https://blog.openstreetmap.org/2015/02/15/openstreetmap-local-chapters-welcome-iceland/
