### ISSUE TITLE
SOTM 2015

### ISSUE THREAD

**Issue by mvexel** [osm-cwg/posts#6]
From RobN:

Hi CWG members,

Can you prep the following for the openstreetmap blog site. If I don't hear back from any other SotM-Wg members soon then this will be published next week.

Best,
Rob

On 16 February 2015 at 13:00, Rob Nickerson <rob.j.nickerson@gmail.com> wrote:
Hi,

Draft text. I've avoided the nitty gritty detail of what went wrong, but have included some insights in to what SotM working group will be doing next (we should get that draft written up as soon as possible). I believe that our actions over the next 3 months are as important when it comes to regaining trust.

Henk, was SotM discussed at the recent board face-to-face? 

---- Proposed blog post text ----

OpenStreetMap events in 2015
The OpenStreetMap Foundation has been organising the annual State of the Map (SotM) conference since 2007. These events have proved popular with our community and have grown from a few dozen attendees to a high of 300 attendees at SotM 2013, in Birmingham UK.
This year we had two good bids in to host SotM 2015. Unfortunately in both cases there were issues beyond our control which caused concerns whether we could make this into a success. The SotM working group, with the support of the OSMF board, has therefore agreed that there will be no OSMF organised conference this year.
As the OpenStreetMap community has grown over the last 10 years so has the conference scene. Although there will be no OSMF organised conference this year there are still a number of non-OSMF conferences, including SotM-US at the UN's New York headquarters in June, and SotM-Scotland in October. There are also many webinars, mapping parties, hack events and socials planned for 2015.
<<<Please insert image https://www.flickr.com/photos/mukluk/434709325  with caption "SotM-US will be held at the UN headquarters in New York, 6-8 June 2015 (image CC BY 2.0 Dan McKay)">>>
The SotM working group has taken on a number of new members to support our efforts in 2015, 2016 and beyond. We are currently drafting a proposal on the future of SotM in which we are looking at the role of SotM within the project and how the OSMF SotM relates to the various regional events. We already have some views but we encourage you to share yours in the comments below.
Preparations for State of the Map 2016 will be starting soon and we encourage local groups who may be interested in hosting SotM in their home country to contact us early.

**Comment by mvexel** [comment]
Created [this gist](https://gist.github.com/mvexel/fac2a4951427f4decae1), please fork and suggest improvements.

**Comment by mvexel** [comment]
when does this need to go out?

**Comment by harry-wood** [comment]
POSTED https://blog.openstreetmap.org/2015/02/25/openstreetmap-events-in-2015/

There was some discussion on the CWG list about this. Bit contentious, but we had a reasonable level of agreement that this text is OK.
